project:
  type: website
  output-dir: docs
  resources: audio/
  preview:
    host: 0.0.0.0
    port: 5500

website:
  title: "KARES Blog Series"
  navbar:
    left:
      - text: "Home"
        href: about.qmd
      - icon: twitter
        href: https://twitter.com
  reader-mode: true
  page-navigation: true
  page-footer: "Copyright ©2022 KARES Foundation - KDM5C Advocacy, Research, Education & Support"
 
#         
# format:
#   html:
#     # theme:
#     #   - litera
#     #   - _brand.yml
#     #   - style
#     toc: true
   
brand: _brand.yml




